name: $(Build.SourceBranchName)_$(Build.Reason)_$(devops_buildNumber)

pr:
  branches:
    include:
    - master
    - dev

trigger:
  branches:
    include:
    - dev
    - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  devops_buildNumber: $[counter(format(''), 1500)]
  APPVEYOR_REPO_BRANCH: $[coalesce(variables['System.PullRequest.TargetBranch'], variables['Build.SourceBranchName'])]
  APPVEYOR_REPO_COMMIT: $(Build.SourceVersion)

steps:
- task: PowerShell@2
  inputs:
    filePath: '.\getTools.ps1'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Set-Location .\Functions.Templates
          $hasTag = Test-Path env:APPVEYOR_REPO_TAG_NAME
          if ($hasTag)
          {
            msbuild Functions.Templates.csproj /p:TemplateVersion=$env:APPVEYOR_REPO_TAG_NAME /target:PortalTemplatesPkg /target:VisualStudioTemplates  
          } else {
            msbuild Functions.Templates.csproj /p:TemplateVersion=$env:APPVEYOR_BUILD_VERSION /target:PortalTemplatesPkg /target:VisualStudioTemplates
          }