name: $(Build.SourceBranchName)_$(Build.Reason)_$(devops_buildNumber)

pr:
  branches:
    include:
    - master
    - dev

trigger:
  branches:
    include:
    - dev
    - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  devops_buildNumber: $[counter(format('3.0.'), 11000)]
  APPVEYOR_REPO_BRANCH: $[coalesce(variables['System.PullRequest.TargetBranch'], variables['Build.SourceBranchName'])]
  APPVEYOR_REPO_COMMIT: $(Build.SourceVersion)
  APPVEYOR_BUILD_VERSION: '3.0.10'

steps:
- task: PowerShell@2
  inputs:
    filePath: '.\getTools.ps1'
- task: MSBuild@1
  inputs:
    solution: '.\Functions.Templates\Functions.Templates.csproj'
    msbuildVersion: '4.0'
    msbuildArguments: '/p:TemplateVersion=3.0.1 /target:PortalTemplatesPkg /target:VisualStudioTemplates'